// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzFZgcgGB0IQxn_wr8N8IygPMKMVzj9bA',
    appId: '1:430630607289:android:94c2e9a1d12e8ccbae3e68',
    messagingSenderId: '430630607289',
    projectId: 'cinemovidaapp',
    databaseURL: 'https://cinemovidaapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cinemovidaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ-LW-kE608pMdrhuYr3TVqL0LNVcsTIY',
    appId: '1:430630607289:ios:e87ef29fd9d5dfcfae3e68',
    messagingSenderId: '430630607289',
    projectId: 'cinemovidaapp',
    databaseURL: 'https://cinemovidaapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cinemovidaapp.appspot.com',
    iosClientId: '430630607289-irsa6fle4acdj5t3vtjtl6p81aq6l30n.apps.googleusercontent.com',
    iosBundleId: 'com.example.appCinemovida',
  );
}
